"""
Django settings for pikabot_graphs project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'au66frr&ce%46%2p72bu7ui97i!i-9v-%*ltwc^)n18kxa&6r*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'pikabu_new_year_18_game_app.apps.PikabuNewYear18GameAppConfig',
    'communities_app.apps.CommunitiesAppConfig',
    'fakeadmin.apps.FakeadminConfig',
    'core.apps.CoreConfig',
    'api.apps.ApiConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pikabot_graphs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'frontend/dist')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pikabot_graphs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.\
password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.\
password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.\
password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.\
password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
ANGULAR_STATIC_URL = '/assets/'
ANGULAR_STATIC_ROOT = os.path.join(BASE_DIR, 'frontend/dist/assets')
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
ANGULAR_ROOT = os.path.join(BASE_DIR, 'frontend/dist')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media'),
]

# rest

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}

# Bot settings

USERS_MODULE = {
    'MIN_UPDATING_PERIOD': 60 * 60 * 6,
    'MAX_UPDATING_PERIOD': 60 * 60 * 24 * 7,
    'MIN_UPDATING_DELTA': 60,
    'MAX_UPDATING_DELTA': 3 * 60 * 60,
    'RESTORE_UPDATING_PERIOD_COEFFICIENT': 2,
}

COMMUNITIES_MODULE = {
    'UPDATING_PERIOD': 1 * 60 * 60
}

BOT_CONCURRENT_TASKS = 100

# / Bot settings

ALLOWED_PUSH_USERS_SESSIONS = []