# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('commentsCount', models.IntegerField(default=0)),
                ('postsCount', models.IntegerField(default=0)),
                ('hotPostsCount', models.IntegerField(default=0)),
                ('plusesCount', models.IntegerField(default=0)),
                ('minusesCount', models.IntegerField(default=0)),
                ('lastUpdateTimestamp', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserDataEntry',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('commentsCount', models.IntegerField()),
                ('postsCount', models.IntegerField()),
                ('hotPostsCount', models.IntegerField()),
                ('plusesCount', models.IntegerField()),
                ('minusesCount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
            options={
                'db_table': 'user_data_entry',
            },
        ),
    ]
