# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentsCountEntry',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserHotPostsCountEntry',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserMinusesCountEntry',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlusesCountEntry',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPostsCountEntry',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRatingEntry',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdataentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDataEntry',
        ),
    ]
