# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170909_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribersCountEntry',
            fields=[
                ('timestamp', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
